### ISSUE TITLE
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'

### ISSUE THREAD

**Issue by GregBowyer** [ali5h/rules_pip#13]
Any ideas on why this happens in a minimal docker container?

```
INFO: Call stack for the definition of repository 'py_deps' which is a pip_import (rule definition at /root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/defs.bzl:49:14):                                                      
 - /stuff/third_party/python/deps.bzl:14:5
 - /stuff/WORKSPACE:92:1
ERROR: An error occurred during the fetch of repository 'py_deps':
   pip_compile failed:  (Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/src/compile.py", line 3, in <module>                                                                                                                                
    from piptools.scripts import compile
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 11, in <module>                                                                                                   
    from .._compat import install_req_from_line, parse_requirements
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/__init__.py", line 7, in <module>                                                                                                   
    from .pip_compat import (
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 54, in <module>                                                                                                
    cmdoptions = do_import("cli.cmdoptions", old_path="cmdoptions")
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 37, in do_import                                                                                               
    return getattr(imported, package)
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'
)
ERROR: no such package '@py_deps//': pip_compile failed:  (Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/src/compile.py", line 3, in <module>                                                                                                                                
    from piptools.scripts import compile
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 11, in <module>                                                                                                   
    from .._compat import install_req_from_line, parse_requirements
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/__init__.py", line 7, in <module>                                                                                                   
    from .pip_compat import (
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 54, in <module>                                                                                                
    cmdoptions = do_import("cli.cmdoptions", old_path="cmdoptions")
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 37, in do_import                                                                                               
    return getattr(imported, package)
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'
)
ERROR: no such package '@py_deps//': pip_compile failed:  (Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/src/compile.py", line 3, in <module>                                                                                                                                
    from piptools.scripts import compile
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 11, in <module>                                                                                                   
    from .._compat import install_req_from_line, parse_requirements
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/__init__.py", line 7, in <module>                                                                                                   
    from .pip_compat import (
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 54, in <module>                                                                                                
    cmdoptions = do_import("cli.cmdoptions", old_path="cmdoptions")
  File "/root/.cache/bazel/_bazel_root/5d28f597b39547cacd9fe873932105d8/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 37, in do_import                                                                                               
    return getattr(imported, package)
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'
)
```

**Comment by ali5h** [comment]
my guess is global pip installation is somehow being picked up and is breaking pip-compile

**Comment by ali5h** [comment]
do you have any repo to reproduce this issue?

**Comment by prebeta** [comment]
I was able to hit something similar on a machine that has pip 9.0.3 installed:

```
pip --version
pip 9.0.3 from /usr/local/lib/python2.7/dist-packages/pip-9.0.3-py2.7.egg (python 2.7)
```

When I try to build something using pip_import, I get: 

```
ERROR: no such package '@common_pip2_requirements//': pip_import failed:  (Traceback (most recent call last):
  File "/mnt/bazel_cache_for_push/_bazel_push/0ec4bbf6f0f556e215284fdcb91dc850/external/com_github_ali5h_rules_pip/src/piptool.py", line 6, in <module>
    from pip._internal.req.req_file import parse_requirements
ImportError: No module named _internal.req.req_file
)
```

**Comment by prebeta** [comment]
I suspect it's because we call the python script directly instead of calling a bazel built binary target https://github.com/ali5h/rules_pip/blob/master/defs.bzl#L65.

I think I found a workaround by using `cfg = "target"` instead of "host". https://github.com/prebeta/rules_pip/commit/b5d0960453d6c3c7b5176d65fa1f39597e5b23a6

**Comment by ali5h** [comment]
i cannot reproduce this, it would be great if someone can create a sample repo with Dockerfile for environment so i can debug it

**Comment by jullianoacqio** [comment]
I am facing the same problem, and I don't have the pip installed on my host.

**Comment by jullianoacqio** [comment]
To complete.
I made the modification suggested by @prebeta and the problem persists.
My environment is:
debian buster from the docker image: https://hub.docker.com/layers/openjdk/library/openjdk/8u252-jdk-slim/images/sha256-96e12e6342dc5afe726d4f4a9c5ef488ebf0686271902ac6fb6001de6040a5f1?context=explore
Bazelisk: v1.5.0
Bazel project: 3.2.0
Python: 3.7.3

This is the error I get when executing bazel sync.
`ERROR: An error occurred during the fetch of repository 'watchersyncdb_pip_deps':
   pip_compile failed:  (Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/src/compile.py", line 3, in <module>
    from piptools.scripts import compile
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 11, in <module>
    from .._compat import install_req_from_line, parse_requirements
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/__init__.py", line 7, in <module>
    from .pip_compat import (
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 54, in <module>
    cmdoptions = do_import("cli.cmdoptions", old_path="cmdoptions")
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 37, in do_import
    return getattr(imported, package)
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'
)
ERROR: no such package '@watchersyncdb_pip_deps//': pip_compile failed:  (Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/src/compile.py", line 3, in <module>
    from piptools.scripts import compile
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/scripts/compile.py", line 11, in <module>
    from .._compat import install_req_from_line, parse_requirements
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/__init__.py", line 7, in <module>
    from .pip_compat import (
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 54, in <module>
    cmdoptions = do_import("cli.cmdoptions", old_path="cmdoptions")
  File "/root/.cache/bazel/_bazel_root/b6f7609a6ec784840d69de16ffda46a5/external/com_github_ali5h_rules_pip/third_party/py/piptools/_compat/pip_compat.py", line 37, in do_import
    return getattr(imported, package)
AttributeError: module 'pip._internal.cli' has no attribute 'cmdoptions'
)`

**Comment by jullianoacqio** [comment]
I am now testing the same configuration described above, but with Debian Stretch and Python 3.5.
Everything seems to be working normally.

**Comment by ali5h** [comment]
that docker image does not seem to have python installed, are you adding it yourself?

**Comment by jullianoacqio** [comment]
yes @ali5h. 
I install via apt-get from a dockerfile derived from the image mentioned above.
This would be a basic dockerfile for testing.
```
FROM openjdk:8u252-jdk-slim as bazel

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl="7.52*" \
    g++="4:6*" \
    zlib1g-dev="1:1.2*" \
  && rm -rf /var/lib/apt/lists/*

RUN BAZEL_VERSION="3.3.0" \
  && curl -o bazel.deb -fsSL \
    "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb" \
  && dpkg -i bazel.deb \
  && rm -f bazel.deb \
  && unset BAZEL_VERSION

FROM bazel

**Comment by jullianoacqio** [comment]
Interesting.
As I mentioned earlier, I am testing with python 3.5 and everything is working normally.
These are the python packages I have installed on my debian streach docker image:
```
dh-python/now 2.20170125 all [installed,local]
libpython-stdlib/now 2.7.13-2 amd64 [installed,local]
libpython2.7-minimal/now 2.7.13-2+deb9u3 amd64 [installed,local]
libpython2.7-stdlib/now 2.7.13-2+deb9u3 amd64 [installed,local]
libpython3-stdlib/now 3.5.3-1 amd64 [installed,local]
libpython3.5-minimal/now 3.5.3-1+deb9u1 amd64 [installed,local]
libpython3.5-stdlib/now 3.5.3-1+deb9u1 amd64 [installed,local]
python/now 2.7.13-2 amd64 [installed,local]
python-bzrlib/now 2.7.0+bzr6619-7+deb9u1 amd64 [installed,local]
python-cffi-backend/now 1.9.1-2 amd64 [installed,local]
python-configobj/now 5.0.6-2 all [installed,local]
python-crypto/now 2.6.1-7 amd64 [installed,local]
python-cryptography/now 1.7.1-3+deb9u2 amd64 [installed,local]
python-enum34/now 1.1.6-1 all [installed,local]
python-httplib2/now 0.9.2+dfsg-1 all [installed,local]
python-idna/now 2.2-1 all [installed,local]
python-ipaddress/now 1.0.17-1 all [installed,local]
python-jinja2/now 2.8-1 all [installed,local]
python-markupsafe/now 0.23-3 amd64 [installed,local]
python-minimal/now 2.7.13-2 amd64 [installed,local]
python-paramiko/now 2.0.0-1 all [installed,local]
python-pkg-resources/now 33.1.1-1 all [installed,local]
python-pyasn1/now 0.1.9-2 all [installed,local]
python-setuptools/now 33.1.1-1 all [installed,local]
python-six/now 1.10.0-3 all [installed,local]
python-yaml/now 3.12-1 amd64 [installed,local]
python2.7/now 2.7.13-2+deb9u3 amd64 [installed,local]
python2.7-minimal/now 2.7.13-2+deb9u3 amd64 [installed,local]
python3/now 3.5.3-1 amd64 [installed,local]
python3-minimal/now 3.5.3-1 amd64 [installed,local]
python3.5/now 3.5.3-1+deb9u1 amd64 [installed,local]
python3.5-minimal/now 3.5.3-1+deb9u1 amd64 [installed,local]
```
Regarding my req files, I don't have the pip package. And yet, it works.
This is my req file:
```
attrs==19.3.0
azure-core==1.5.0
azure-storage-blob==12.3.1
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
elasticsearch==7.7.0
idna==2.9
importlib-metadata==1.6.0
isodate==0.6.0
jsonschema==3.2.0
msrest==0.6.13
oauthlib==3.1.0
pycparser==2.20
pyrsistent==0.16.0
python-json-logger==0.1.11
requests-oauthlib==1.3.0
requests==2.23.0
schedule==0.6.0
six==1.14.0
structlog==20.1.0
urllib3==1.25.9
zipp==1.2.0
```

**Comment by ali5h** [comment]
it should work without pip

**Comment by jullianoacqio** [comment]
@ali5h After installing the `python3-distutils` and  `python3.7-dev` packages everything works.
