### ISSUE TITLE
grpcio error

### ISSUE THREAD

**Issue by rockwotj** [ali5h/rules_pip#9]
When loading `requirement("grpcio")` I get the following error, do you understand what is going on?
```
Traceback (most recent call last):
  File "/app/demo/feed/nextbus_feed.binary.runfiles/firestore_s2/demo/feed/nextbus_feed.py", line 6, in <module>
    from google.cloud import firestore
  File "/app/demo/feed/nextbus_feed.binary.runfiles/pypi__36__google_cloud_firestore_1_6_0/google/cloud/firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "/app/demo/feed/nextbus_feed.binary.runfiles/pypi__36__google_cloud_firestore_1_6_0/google/cloud/firestore_v1/__init__.py", line 22, in <module>
    from google.cloud.firestore_v1._helpers import GeoPoint
  File "/app/demo/feed/nextbus_feed.binary.runfiles/pypi__36__google_cloud_firestore_1_6_0/google/cloud/firestore_v1/_helpers.py", line 21, in <module>
    import grpc
  File "/app/demo/feed/nextbus_feed.binary.runfiles/pypi__36__grpcio_1_26_0/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc'
```

**Comment by rockwotj** [comment]
Nevermind, I was running this in a docker container after building locally, so the wrong native deps were built.
